export const GAME_CONSTANTS = {
  DEFAULT_STARTING_CHIPS: 1000,
  DEFAULT_BOOT_AMOUNT: 50,
  MAX_PLAYERS_PER_ROOM: 4,
  AUTO_FOLD_TIMEOUT_MS: 30000,
  ROOM_ID_LENGTH: 6,
  PLAYER_ID_LENGTH: 8,
  MIN_USERNAME_LENGTH: 3,
  MAX_USERNAME_LENGTH: 12,
};
